### ISSUE TITLE
🐛 Bug Report: Microsoft OAuth Error

### ISSUE THREAD

**Issue by SecureCPU** [stonith404/pingvin-share#322]
### 👟 Reproduction steps

Try to login using a Microsoft account

### 👍 Expected behavior

Should login using the Microsoft account

### 👎 Actual Behavior

I get the following error: {"statusCode":500,"message":"Internal server error"}

I have set the Web Redirect URIs in the Microsoft Application as: "https://example.com/api/oauth/callback/microsoft"

### 🌐 Browser

Chrome

**Comment by SecureCPU** [comment]
I'm getting the same error with github, and with discord i get the error that says "Can't get email address from this Discord account."

I'm not sure what i'm doing wrong.

**Comment by stonith404** [comment]
Can you share the server logs? The Discord bug is related to #302

**Comment by SecureCPU** [comment]
This is the Log when I tried the Microsoft Login:

`[Nest] 46  - 11/09/2023, 6:44:14 PM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'nonce')
TypeError: Cannot read properties of null (reading 'nonce')
    at MicrosoftProvider.getUserInfo (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:84:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuthController.callback (/opt/app/backend/dist/src/oauth/oauth.controller.js:50:22)`

**Comment by SecureCPU** [comment]
This is the error I got when I tried Github:

`[Nest] 46  - 11/09/2023, 6:45:50 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes')
    at GitHubProvider.getUserInfo (/opt/app/backend/dist/src/oauth/provider/github.provider.js:50:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuthController.callback (/opt/app/backend/dist/src/oauth/oauth.controller.js:50:22)`

**Comment by SecureCPU** [comment]
Here is the full log i download:

[pingvin-file-share-pingvin-share-1_logs.txt](https://github.com/stonith404/pingvin-share/files/13311729/pingvin-file-share-pingvin-share-1_logs.txt)

**Comment by chrisburkey** [comment]
Having the same issue.  Here is the output of my last attempt at using microsoft authentication: 
{"statusCode":500,"message":"Internal server error"}

Logs:
[Nest] 47  - 11/09/2023, 7:47:50 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 47  - 11/09/2023, 7:47:53 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 47  - 11/09/2023, 7:47:53 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 47  - 11/09/2023, 7:48:07 PM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'nonce')
TypeError: Cannot read properties of null (reading 'nonce')
    at MicrosoftProvider.getUserInfo (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:84:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuthController.callback (/opt/app/backend/dist/src/oauth/oauth.controller.js:50:22)
[Nest] 47  - 11/09/2023, 7:48:07 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by stonith404** [comment]
@zz5840 Do you have an idea why this could happen?

**Comment by zz5840** [comment]
@stonith404 I'm still finding the cause of this error:

```
[Nest] 46  - 11/09/2023, 5:05:11 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Seems all OAuth errors are caused by this, but I don't know why user could be null.

https://github.com/stonith404/pingvin-share/blob/5503e7a54f5db2026485eb0f52399646eeb86f80/backend/src/user/user.controller.ts#L28-L34

**Comment by zz5840** [comment]
@stonith404 Oh sorry, I think I found the cause. I was so remiss that I wrote a wrong request URL, and I even don't know how it passed my test.

**Comment by zz5840** [comment]
@SecureCPU @chrisburkey Issues in GitHub and Discord has been fixed please test it after the dev image being published.

Could you tell me which url this error occurs at:

```
{"statusCode":500,"message":"Internal server error"}
```

**Comment by stonith404** [comment]
@zz5840 Thank you for your help! The dev image is ready.

**Comment by zz5840** [comment]
@chrisburkey @SecureCPU I have updated the docs of Microsoft authentication, please check it and confirm your config is correct.
https://github.com/stonith404/pingvin-share/blob/af8932094a1de7862f05ea103b58207b7a5df798/docs/oauth2-guide.md#microsoft

**Comment by SecureCPU** [comment]
Its still not working, Can anyone send me screen shots of what its supposed to look like?

**Comment by zz5840** [comment]
@SecureCPU Are you using stable image or dev image?

**Comment by SecureCPU** [comment]
These are my settings:
![brave_DjcYqV43JR](https://github.com/stonith404/pingvin-share/assets/99109793/94453132-3d35-4df9-993e-a9c5f4fe09b2)
![brave_lO5pdBUzyt](https://github.com/stonith404/pingvin-share/assets/99109793/a4f7d263-e8c3-49ef-9190-426bcdab9339)
![brave_k4QCvi6MGU](https://github.com/stonith404/pingvin-share/assets/99109793/ceaae3d8-7e81-4d6b-aea4-5cb23f1d101e)

**Comment by SecureCPU** [comment]
I'm using the stable image

**Comment by SecureCPU** [comment]
and its behind NPM proxy and cloudflare proxy, but doesn't have any rules or blocks applied

**Comment by SecureCPU** [comment]
should i try the Dev image?

**Comment by SecureCPU** [comment]
I'm trying the Dev image now.

**Comment by zz5840** [comment]
Sorry, but dev image may not solve your issue too. You can try to create a personal Microsoft accounts only app in Microsoft Entra and use consumer for tenant.

**Comment by zz5840** [comment]
![image](https://github.com/stonith404/pingvin-share/assets/16662647/990f089e-746d-4808-b2f8-d205ed4b2739)
Your error may be caused by this.

**Comment by SecureCPU** [comment]
So my company is a verified, and i added it to the app when i created it:
![brave_cBv58MXpZl](https://github.com/stonith404/pingvin-share/assets/99109793/a16e0231-d1fd-4d92-b151-7c6f55ffc44a)

**Comment by SecureCPU** [comment]
But I still get this error: 
![image](https://github.com/stonith404/pingvin-share/assets/99109793/d950025f-2433-417a-b8df-296f1f718243)

**Comment by SecureCPU** [comment]
But the Dev version fixed the github and discord for me. that worked perfectly. Thank you so much!!

**Comment by zz5840** [comment]
Ok, I have update the code to display the detail error when authentication failed, please try it again after @stonith404 updating the dev image.

**Comment by zz5840** [comment]
> But I still get this error: 
> ![image](https://user-images.githubusercontent.com/99109793/282100700-d950025f-2433-417a-b8df-296f1f718243.png)

By the way, how did you see this error message? I think I have made all error to show on error page rather than a raw JSON.

**Comment by SecureCPU** [comment]
this is what showed on the website once i authenticated my Microsoft account.

**Comment by zz5840** [comment]
@SecureCPU Ok, the dev image has been updated, please test the dev image again.

**Comment by SecureCPU** [comment]
k. updating now

**Comment by zz5840** [comment]
> this is what showed on the website once i authenticated my Microsoft account.

On which url this error shows? `/api/oauth/auth/microsoft` or `/api/oauth/callback/microsoft`

**Comment by SecureCPU** [comment]
/api/oauth/callback/microsoft

**Comment by SecureCPU** [comment]
Still getting the same error.
![image](https://github.com/stonith404/pingvin-share/assets/99109793/94a86e1d-9983-4093-8078-316e330d90f7)

**Comment by SecureCPU** [comment]
This is the full URL when I get that error (Link can only be viewed once.

[CLICK HERE TO VIEW](https://secretshare.net/secret/fd66bab4-d14b-4ee5-92e5-4a8587314521#encryption_key=ckN2k97-vt6FoAoSdwLKCzwdX5rosB9n)

**Comment by zz5840** [comment]
Ok, I see, but it's time for me to sleep, I'll look into it tomorrow.

**Comment by zz5840** [comment]
@SecureCPU It still shows `Cannot read properties of null (reading 'nonce')`, right?

**Comment by SecureCPU** [comment]
> @SecureCPU It still shows `Cannot read properties of null (reading 'nonce')`, right?

I didn't see that error, just the one I mentioned before. But Microsoft still doesn't work.

**Comment by zz5840** [comment]
> This is the full URL when I get that error (Link can only be viewed once.
> 
> [CLICK HERE TO VIEW](https://secretshare.net/secret/fd66bab4-d14b-4ee5-92e5-4a8587314521#encryption_key=ckN2k97-vt6FoAoSdwLKCzwdX5rosB9n) 

After you get this URL, please use curl to request the token and check outputs.

You can send it to my email i#qingfu.dev if it contains sensitive information.

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&grant_type=authorization_code&code=YOUR_CODE&redirect_uri=YOUR_APP_URL/api/oauth/callback/microsoft' https://login.microsoftonline.com/common/oauth2/v2.0/token`

Don't forget to replace the variable in URL. The code is from URL you get from last step, it's a bit long, please be careful with the boundary.

BTW, please re-open the PR.

**Comment by SecureCPU** [comment]
I found the issue...

So I entered the wrong value for the Client Secret, I used the Client Secret ID instead of the Client Secret Value.

Once I figured that out, I reissued the Client Secret and used the value instead of the ID and it worked like a charm.

Sorry for the trouble, ended up being user error. feel really stupid i missed the 2 up on this application.

**Comment by rewulff** [comment]
Had the same issue for another reason.
JSON DEBUG: "Cannot GET //api/oauth/auth/microsoft"

Simple solution:

In Pingvin-Settings I setted up my domain with / at the end. This leaded to <domain>//api which fails.

Just make sure to end your Domain in Settings to TLD without / at the end.

**Comment by EngKarl** [comment]
How do i change the Microsoft cer, Client Secret and so on over docker? The old cert is not working anymore and i created a new one, but dont find where to switch it. The dokumentation is not clear for me...
